src/apps_web/web_page/urls.py
from django.conf.urls import url
from .views import (payment_methods,
    pages, contact, contact_thanks, complaints_book, complaints_book_generate, question_response,
    question_response_question)

urlpatterns = [
    # url(r"^preguntas-frecuentes/$", question, name="question"),
    url(r"^contacto/$", contact, name="contact"),
    url(r"^libro-reclamaciones/$", complaints_book, name="complaints_book"),
    url(r"^contacto-gracias/$", contact_thanks, name="contact_thanks"),
    url(r"^preguntas-frecuentes/$", question_response, name="question_response"),
    url(r"^preguntas-frecuentes/(?P<slug>[\w-]+)/$", question_response_question, name="question_response_question"),
    # url(r"^formas-pago/$", payment_methods, name="payment_methods"),
    url(r'^libro-reclamaciones/(?P<uuid_hash>[\w-]+)$', complaints_book_generate,
        name='complaints_book_generate'),
    url(r"^(?P<slug>[\w-]+)/$", pages, name="pages"),
]

src/apps_web/web_system/urls.py
from django.conf.urls import url
from .views import (home, login_register, account, test_email,
    logout_view, my_address, my_address_edit, my_order, my_order_detail, my_address_create,
    follow_orders, testing_view, create_account)
from .api_views import SuscriptionAPI

urlpatterns = [
    url(r"^$", home, name="home"),
    url(r"^ingresar/$", login_register, name="login_register"),
    url(r"^crear-cuenta/$", create_account, name="create_account"),
    url(r"^mi-cuenta/$", account, name="account"),
    url(r"^mis-direcciones/$", my_address, name="my_address"),
    url(r"^mis-direcciones/(?P<pk>\d+)/$", my_address_edit, name="my_address_edit"),
    url(r"^test-email/$", test_email, name="test_email"),
    url(r"^salir/$", logout_view, name="logout_view"),
    url(r"^mis-ordenes/$", my_order, name="my_order"),
    url(r"^mis-direcciones/crear/$", my_address_create, name="my_address_create"),
    url(r"^mis-ordenes/(?P<pk>\d+)/$", my_order_detail, name="my_order_detail"),
    url(r"^sigue-orden/$", follow_orders, name="follow_orders"),
    url(r"^testing_view/$", testing_view, name="testing_view"),
    url(r"^api-suscripcion/$", SuscriptionAPI.as_view(), name="api_suscripcion"),
]

src/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]  + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    url(r'^api-v1/', include([
        url(r'security/',
            include('apps_base.security.urls', namespace='security')),
        url(r'influencer/',
            include('apps_base.influencer.urls', namespace='influencer')),
        url(r'category/',
            include('apps_base.category.urls', namespace='category')),
        url(r'product/',
            include('apps_base.product.urls', namespace='product')),
        url(r'family/',
                include('apps_base.family.urls', namespace='family')),
        url(r'attribute/',
            include('apps_base.attribute.urls', namespace='attribute')),
        url(r'pages/',
            include('apps_base.pages.urls', namespace='pages')),
        url(r'form/',
            include('apps_base.form.urls', namespace='form')),
        url(r'ubigeo/', include('apps_base.ubigeo.urls', namespace='ubigeo')),
        url(r'payment/', include('apps_base.payment.urls', namespace='payment')),
        url(r'customers/', include('apps_base.customers.urls', namespace='customers')),
        url(r'order/', include('apps_base.order.urls', namespace='order')),
        url(r'configuration/', include('apps_base.configuration.urls', namespace='configuration')),
        url(r'shipping/', include('apps_base.shipping.urls', namespace='shipping')),
        url(r'promotion/', include('apps_base.promotion.urls', namespace='promotion')),
        url(r'custom_auth/', include('apps_base.custom_auth.urls', namespace='custom_auth'))
    ])),
    url(r'^api-influencer/', include('admin_influencer.urls', namespace='admin_influencer')),
    url(r'^', include('apps_web.web_system.urls', namespace='web_system')),
    url(r'^', include('apps_web.web_product.urls', namespace='web_product')),
    url(r'^', include('apps_web.web_cart.urls', namespace='web_cart')),
    url(r'^', include('apps_web.web_order.urls', namespace='web_order')),
    url(r'^', include('apps_web.web_page.urls', namespace='web_page')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"/>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}?v=0.0.9"/>
    <link rel="stylesheet" href="{% static 'css/jquery.mmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}?v=0.0.9"/>
    <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}?v=0.0.9"/>
    <link rel="stylesheet" href="{% static 'css/styl.css' %}?v=0.0.9"/>

    <link rel="shortcut icon" href="/favicon.ico"/>
    {% block css %}

    {% endblock css %}
</head>
<body class='home'>
  <div id="page" class="wrapper">

    {% include "./header.html" %}
    {% include "./menu.html" %}
    <div class="page">
        {% block content %}

        {% endblock content %}

    </div>
    <cart-view ></cart-view>
    {% include "./footer.html" %}

  </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
        var staticURL = '{{STATIC_URL}}';
    </script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.js' %}?v=0.0.9"></script>
    <script src='{% static "js/jquery.mmenu.js" %}'></script>
    {% if debug %}
        <script src='http://localhost:8080/static/app/app.js'></script>
    {% else %}
        <script src='{% static "app/app.js" %}?v=0.0.9'></script>

    {% endif %}
    {% block js %}

    {% endblock js %}
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}?v=0.0.9"></script>
    <script>
        jQuery(document).ready(function($) {
            $(".menu_categorias .link_menu").click(function(event) {
                /* Act on the event */
                event.preventDefault();
                $('.menu_categorias li').removeClass('active')
                $('.submenu--active').removeClass('submenu--active')
                $(this).parent().addClass('active')
                $(this).parent().find('.submenu').addClass('submenu--active')
            });
            window.onclick = function(event) {
                console.log(event.target, '--')
                // if (event.target == $(".modal-open .in")[0]) {
                //     $(".close_modal").trigger('click')
                // }
            }
            $(".header__account").click(function(event) {
                /* Act on the event */
                event.preventDefault()
                $(".header__search").toggleClass('hidden-xs')
                $(".header__search").find('input').trigger('click')
            });
        });
    </script>
</body>
</html>

src/templates/common/base_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"/>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}?v=0.0.8"/>
    <link rel="stylesheet" href="{% static 'css/styl.css' %}?v=0.0.8"/>
    <link rel="shortcut icon" href="/favicon.ico"/>
    {% block css %}

    {% endblock css %}
</head>
<body>
  <div id="page" class="wrapper">

    {% include "./header_order.html" %}
    {% block content %}

    {% endblock content %}

    {% include "./footer.html" %}

  </div>
    {% block before_js %}

    {% endblock before_js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    {% if debug %}
        <script src='http://localhost:8080/static/app/app.js'></script>
    {% else %}
        <script src='{% static "app/app.js" %}?v=0.0.4'></script>

    {% endif %}
    {% block js %}

    {% endblock js %}

</body>
</html>

src/templates/common/footer.html
{% load static %}
<div id="footer">
  <div class="container">
    <div class="row">

      <div class="col-md-4 col-sm-4 col-xs-6 col-mv">
        <div class="block-list">
          <h3>Servicio al cliente</h3>
          <div class="footer_enlaces">
            <ul class="service_client">
              {% for page_pro in pages_processors %}
                <li><a class=''  href='{% url "web_page:pages" page_pro.slug %}'>{{page_pro.name}}</a></li>
              {% endfor %}
              <li><a href='{% url "web_page:question_response" %}'>Preguntas Frecuentes</a></li>

            </ul>
            <ul class="service_client">
              <li><a href='{% url "web_system:follow_orders" %}'>Sigue tu orden</a></li>
              <li><a href="{% url 'web_page:contact' %}">Soporte al cliente</a></li>
              <li><a href="{% url 'web_page:complaints_book' %}">Libro de reclamaciones</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-2 col-sm-2 col-xs-6 col-mv">
        <div class="block-list">
          <h3>Mi Cuenta</h3>
          <ul>
            <li><a href='{% url "web_system:login_register" %}'>Ingresar</a></li>
            <li><a href='{% url "web_system:login_register" %}'>Registro</a></li>
            <li><a href='{% url "web_system:my_order" %}'>Mis Ordenes</a></li>
            <li><a href='{% url "web_system:follow_orders" %}'>Sigue tu orden</a></li>
          </ul>
        </div>

      </div>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <div class="block-list">
          <ul class="social">
            {% if configuration_processors.facebook %}
              <li><a target="_blank" href="{{configuration_processors.facebook}}"><i class="fab fa-facebook-f"></i></a></li>
            {% endif %}

            {% if configuration_processors.instagram %}
              <li><a target="_blank" href="{{configuration_processors.instagram}}"><i class="fab fa-instagram"></i></a></li>
            {% endif %}
            {% if configuration_processors.youtube %}
              <li><a target="_blank" href="{{configuration_processors.youtube}}"><i class="fab fa-youtube"></i></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12 col-mv col-xs-12">
        <div class="block-list">
          <h3>Suscribite</h3>
          <div class="w-form">
            <form action="" @submit.prevent='submitSuscription' >
              <input type="text" v-model='emailSuscription' class="text" placeholder="Ingresa tu email" />
              <button type="submit"  class="btn"><i class="fa fa-chevron-right"></i></button>
              <br></br>
              <p v-if='showEmailSuscription'>#{messageEmailSuscription}</p>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/templates/common/header.html
{% load static %}
<header id="header" class="full-width">
  <div class="container cf">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-md-offset-5 col-sm-offset-5 col-xs-12 text-center">
        <a href="#menu" class="navbar-toggle collapsed"><span class="sr-only">...</span><i aria-hidden="true" class="fas fa-bars"></i></a>
        <div class="wrap-logo">
          <h1 class="logo"><a href="{% url 'web_system:home' %}"></a></h1>
        </div>
        <ul class="list-options">
          <li>
            <a href="{% url 'web_system:account' %}" class="account header__account">
              <img src="{% static 'img/lupa-01.png' %}" width='25' alt="">
            </a>
          </li>
          <li><a href="{% url 'web_product:product_favorites' %}" class="fav"> <img src="{% static 'img/crzn-01.png' %}" width='25' alt=""></a></li>
          <li><a href="#" @click.prevent='changeStatusCartView()' class="shop"> <img src="{% static 'img/bag-01-01.png' %}" width='25' alt=""></a></li>
        </ul>
      </div>
      {% comment %}

      <div class="col-md-5 col-md-push-4 col-sm-8 col-xs-6">
        <ul class="list-options">
          <li><a href="{% url 'web_product:product_favorites' %}" class="fav"> <i class="fa fa-heart"></i><span>Mis Favoritos</span></a></li>
          {% if request.user.is_authenticated %}
            <li class="list-options__menu">
              <a href="" class="account"> <i class="fa fa-user"></i>{{request.user.first_name}}</a>
              <ul class=''>
                <span class='triangle'>

                </span>
                <li>
                  <a href="{% url 'web_system:account' %}"> <i class="fa fa-dashboard"></i> Mi Cuenta</a>
                </li>
                <li>
                  <a href="{% url 'web_system:logout_view' %}"><i class=' fa fa-sign-out'></i>Cerrar sesión</a>
                </li>
              </ul>
            </li>
          {% else %}
            <li><a href="{% url 'web_system:login_register' %}" class="account"> <i class="fa fa-user"></i><span>Ingresar</span></a></li>

          {% endif %}
          <li><a href="#" @click.prevent='changeStatusCartView()' class="shop"> <i class="fa fa-shopping-bag"></i><span>Mis Compras</span></a></li>
        </ul>
      </div>
      {% endcomment %}
      <div class="col-md-3 col-xs-12  col-md-offset-1 col-sm-3 hidden-xs header__search">
        <form method='GET' action='{% url "web_product:product_search" %}' class="wrap-search">
          <input type="text" name='search' placeholder="Buscar"/>
          <div class="wrap-search__icon">
            <img class='hidden-xs' src="{% static 'img/lupa_trans.png' %}" width='19' alt="">
          </div>
        </form>
      </div>
    </div>
  </div>
</header>

src/templates/common/header_order.html
<header id="header" class="full-width">
  <div class="container cf">
    <div class="row">
      <div class="col-md-3">
        <div class="wrap-logo">
          <h1 class="logo"><a href="{% url 'web_system:home' %}">fanntop</a></h1>
        </div>
      </div>
      <div class="col-md-4">

      </div>
      {% comment %}
        <div class="col-md-5">
          <ul class="list-options">
            {% if request.user.is_authenticated %}
              <li><a href="" class="account"> <i class="fa fa-user"></i>{{request.user.first_name}}</a></li>
            {% else %}
              <li><a href="{% url 'web_system:login_register' %}" class="account"> <i class="fa fa-user"></i>Ingresar</a></li>
            {% endif %}
          </ul>
        </div>

      {% endcomment %}
    </div>
  </div>
</header>

src/templates/common/menu.html
{% load static %}
<div id="nav" class="full-width">
  <div class="container">
    <nav class='menu_categorias'>
      <ul>
        <li><a class='link_menu'> Diseñadores</a>
          {% if designers_processors %}
          <div class="submenu">
            <div class="container">
              <ul class='row row__submenu'>
                {% for designer in designers_processors %}
                  <li class=''><a href="{% url 'web_product:influencer_products' designer.slug %}">{{designer.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          {% endif %}
        </li>
        {% for category in categories_processors %}
        <li><a class='link_menu' {% if not category.category_categories.all %}href="{% url 'web_product:category_products' category.slug %}"{% endif %}> {{category.name}}</a>
          {% if category.category_categories.all %}
          <div class="submenu">
            <div class="container">
              <ul class='row'>
                {% for category_child in category.category_categories.all %}
                  <li class=''><a href="{% url 'web_product:category_child_products' category.slug category_child.slug %}">{{category_child.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          {% endif %}
        </li>
        {% endfor %}
        <li><a class='link_menu'> Marcas</a>
          {% if influencers_processors %}
          <div class="submenu">
            <div class="container">
              <ul class='row row__submenu'>
                {% for influencer in influencers_processors %}
                  <li class=''><a href="{% url 'web_product:influencer_products' influencer.slug %}">{{influencer.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          {% endif %}
        </li>

      </ul>
    </nav>
    <nav class="menu_opciones">
      <ul class="list-options">
          <li><a href="{% url 'web_product:product_favorites' %}" class="fav"> <img src="{% static 'img/corazon.png' %}" width='17' alt=""></a></li>
          {% if request.user.is_authenticated %}
            <li class="list-options__menu">
              <a href="" class="account"> <img src="{% static 'img/user.png' %}" width='17' alt=""></a>
             </a>
              <ul class=''>
                <span class='triangle'>
                </span>
                <li>
                  <a href="{% url 'web_system:account' %}"> <i class="fa fa-dashboard"></i> Mi Cuenta</a>
                </li>
                <li>
                  <a href="{% url 'web_system:logout_view' %}"><i class=' fa fa-sign-out'></i>Cerrar sesión</a>
                </li>
              </ul>
            </li>
          {% else %}
            <li><a href="{% url 'web_system:login_register' %}" class="account"> <img src="{% static 'img/user.png' %}" width='17' alt=""></a></li>

          {% endif %}
          <li><a href="#" @click.prevent='changeStatusCartView()' class="shop"> <img src="{% static 'img/mochila.png' %}" width='13' alt=""></a></li>
        </ul>
    </nav>
  </div>
</div>
<nav id="menu" class='mmenu'>
  <ul class='mmenu__ul'>
    {% for category in categories_processors %}
    <li class='mmenu__category'><span>{{category.name}}</span>
      <ul>
        {% for category_child in category.category_categories.all %}
          <li><a href="{% url 'web_product:category_child_products' category.slug category_child.slug %}">{{category_child.name}}</a></li>
        {% endfor %}
      </ul>
    </li>
    {% endfor %}
    {% if request.user.is_authenticated %}
      <li class=''>
        <a href="{% url 'web_system:logout_view' %}">Cerrar sesión</a>
      </li>
    {% else %}
      <li class=''>
        <a href="{% url 'web_system:login_register' %}">Ingresar</a>
      </li>
    {% endif %}
    <li class='mmenu__marcas'><span>Diseñadores</span>
      <ul>
        {% for influencer in designers_processors %}
          <li><a href="{% url 'web_product:influencer_products' influencer.slug %}">{{influencer.name}}</a></li>
        {% endfor %}
      </ul>
    </li>
    <li class='mmenu__marcas'><span>Marcas</span>
      <ul>
        {% for influencer in influencers_processors %}
          <li><a href="{% url 'web_product:influencer_products' influencer.slug %}">{{influencer.name}}</a></li>
        {% endfor %}
      </ul>
    </li>
    <li>
      <h4 class='mmenu__title'>
        MI CUENTA
      </h4>
    </li>
    <li>
      <a href="{% url 'web_system:my_order' %}">Mis ordenes</a>
    </li>
    <li>
      <a href='{% url "web_system:follow_orders" %}'>Sigue tu ordenes</a>
    </li>
    <li>
      <h4 class='mmenu__title'>
        SERVICIO AL CLIENTE
      </h4>
    </li>
    <li><a href='{% url "web_page:question_response" %}'>Preguntas Frecuentes</a></li>
    {% for page_pro in pages_processors %}
      <li><a class=''  href='{% url "web_page:pages" page_pro.slug %}'>{{page_pro.name}}</a></li>
    {% endfor %}
    <li><a href="{% url 'web_page:contact' %}">Soporte al cliente</a></li>
    <li><a href="{% url 'web_page:complaints_book' %}">Libro de reclamaciones</a></li>
  </ul>
</nav>