src/apps_base/ubigeo/urls.py
from django.conf.urls import url
from .views import departamentos, provincias, distritos, ubigeo_full_name

urlpatterns = [
    url(r'^departamentos/$', departamentos, name='api_departamentos'),
    url(r'^provincias/$', provincias, name='api_provincias'),
    url(r'^distritos/$', distritos, name='api_distritos'),
    url(r'^ubigeo-full-name/$', ubigeo_full_name, name='ubigeo_full_name'),
]

src/apps_web/web_page/urls.py
from django.conf.urls import url
from .views import (payment_methods,
    pages, contact, contact_thanks, complaints_book, complaints_book_generate, question_response,
    question_response_question)

urlpatterns = [
    # url(r"^preguntas-frecuentes/$", question, name="question"),
    url(r"^contacto/$", contact, name="contact"),
    url(r"^libro-reclamaciones/$", complaints_book, name="complaints_book"),
    url(r"^contacto-gracias/$", contact_thanks, name="contact_thanks"),
    url(r"^preguntas-frecuentes/$", question_response, name="question_response"),
    url(r"^preguntas-frecuentes/(?P<slug>[\w-]+)/$", question_response_question, name="question_response_question"),
    # url(r"^formas-pago/$", payment_methods, name="payment_methods"),
    url(r'^libro-reclamaciones/(?P<uuid_hash>[\w-]+)$', complaints_book_generate,
        name='complaints_book_generate'),
    url(r"^(?P<slug>[\w-]+)/$", pages, name="pages"),
]

src/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]  + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    url(r'^api-v1/', include([
        url(r'security/',
            include('apps_base.security.urls', namespace='security')),
        url(r'influencer/',
            include('apps_base.influencer.urls', namespace='influencer')),
        url(r'category/',
            include('apps_base.category.urls', namespace='category')),
        url(r'product/',
            include('apps_base.product.urls', namespace='product')),
        url(r'family/',
                include('apps_base.family.urls', namespace='family')),
        url(r'attribute/',
            include('apps_base.attribute.urls', namespace='attribute')),
        url(r'pages/',
            include('apps_base.pages.urls', namespace='pages')),
        url(r'form/',
            include('apps_base.form.urls', namespace='form')),
        url(r'ubigeo/', include('apps_base.ubigeo.urls', namespace='ubigeo')),
        url(r'payment/', include('apps_base.payment.urls', namespace='payment')),
        url(r'customers/', include('apps_base.customers.urls', namespace='customers')),
        url(r'order/', include('apps_base.order.urls', namespace='order')),
        url(r'configuration/', include('apps_base.configuration.urls', namespace='configuration')),
        url(r'shipping/', include('apps_base.shipping.urls', namespace='shipping')),
        url(r'promotion/', include('apps_base.promotion.urls', namespace='promotion')),
        url(r'custom_auth/', include('apps_base.custom_auth.urls', namespace='custom_auth'))
    ])),
    url(r'^api-influencer/', include('admin_influencer.urls', namespace='admin_influencer')),
    url(r'^', include('apps_web.web_system.urls', namespace='web_system')),
    url(r'^', include('apps_web.web_product.urls', namespace='web_product')),
    url(r'^', include('apps_web.web_cart.urls', namespace='web_cart')),
    url(r'^', include('apps_web.web_order.urls', namespace='web_order')),
    url(r'^', include('apps_web.web_page.urls', namespace='web_page')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/templates/pages/complaints_book.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class=" pages">
        <div class="w-body">
          <h2 class='preguntas_frecuentes__title'>Libro de reclamaciones</h2>
          <form class="pages__content" method="POST" action=".">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-10 ">
                <h4 class="w-body__title preguntas_frecuentes__subtitle">1. IDENTIFICACIÓN DEL CONSUMIDOR RECLAMANTE</h4>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.first_name.label_tag}}
                      {{form.first_name|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.last_name.label_tag}}
                      {{form.last_name|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.email.label_tag}}
                      {{form.email|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.phone.label_tag}}
                      {{form.phone|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.type_document.label_tag}}
                      {{form.type_document|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.document.label_tag}}
                      {{form.document|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Departamento</label>
                            <select class="form-control" id='id_shipping-departamento' name="departamento" >
                              <option value="">Seleccione Departamento</option>
                            </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Provincia</label>
                            <select class="form-control" name="provincia" id="id_shipping-provincia">
                              <option value="">Seleccione Provincia</option>
                            </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Distrito</label>
                      {{form.ubigeo|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      {{form.address.label_tag}}
                      {{form.address|add_class:'form-control'}}
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 ">
                <h4 class="w-body__title preguntas_frecuentes__subtitle">2. IDENTIFICACIÓN DEL BIEN CONTRATADO</h4>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Tipo de bien contratado</label>
                      {{form.well_contracted|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Monto</label>
                      {{form.mount|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Número de pedido</label>
                      {{form.pedido|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Descripción</label>
                      {{form.desciption|add_class:'form-control'}}
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 ">
                <h4 class="w-body__title preguntas_frecuentes__subtitle">3. DETALLE DE LA RECLAMACIÓN Y PEDIDO DEL CONSUMIDOR</h4>
                <div class="row">
                  <div class="col-md-12">
                    <p>Reclamo: Disconformidad relacionada a los productos o servicios.</p>
                  </div>
                  <div class="col-md-12">
                    <p>Queja: Disconformidad no relacionada a los productos o servicios; o malestar o descontento respecto a la atención al público.</p>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Tipo de reclamo</label>
                      {{form.type_claim|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Pedido del consumidor</label>
                      {{form.consumers_order|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Detalle del reclamo</label>
                      {{form.detail|add_class:'form-control'}}
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 ">
                <h4 class="w-body__title preguntas_frecuentes__subtitle">4. OBSERVACIONES Y ACCIONES ADOPTADAS POR EL PROVEEDOR</h4>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Descripción</label>
                      {{form.observation|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-12">
                    <button class='btn btn--dark pull-right'>Enviar</button>
                  </div>
                </div>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}
<script>
  jQuery(document).ready(function($) {
    var departamento_initial = $('#id_shipping-departamento')
    departamento_initial.html('')
    var code_departamento = '{{code_departamento}}'
    var code_provincia = '{{code_provincia}}'
    var code_distrito = '{{code_distrito}}'
    $.ajax({
        'url': '{% url "ubigeo:api_departamentos" %}',
        'method': 'GET',
        'success': function (data) {
            departamento_initial.append('<option value="" selected="selected">Seleccione Departamento</option>');
            for (var i = 0; i < data.departamentos.length; i++) {
              if (code_departamento == data.departamentos[i].codigo) {
                departamento_initial.append('<option selected="selected" value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              } else {
                departamento_initial.append('<option value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              }
            }
            if (code_departamento) {
              $('#id_shipping-departamento').trigger('change')
            }
            // provincia.change();
        }
    })
    $('#id_shipping-departamento').change(function(event) {
    /* Act on the event */
      var departamento = $(this).val();
      var provincia = $('#id_shipping-provincia')
      var distrito = $('#id_ubigeo')
      provincia.html('');
      distrito.html('');
      if (departamento) {
        $.ajax({
              'url': '{% url "ubigeo:api_provincias" %}' + '?departamento=' + departamento,
              'method': 'GET',
              'success': function (data) {
                  provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
                  for (var i = 0; i < data.provincias.length; i++) {
                    if (code_provincia == data.provincias[i].codigo) {
                      provincia.append('<option  selected="selected" value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    } else {
                      provincia.append('<option value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    }
                  }
                  if (code_provincia) {
                    $('#id_shipping-provincia').trigger('change')
                  }
                  // provincia.change();
              }
          })
      } else {
        provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
        distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
        code_provincia = ''
      }


    });
    $('#id_shipping-provincia').change(function(event) {
    /* Act on the event */
      var provincia = $(this).val();
      var distrito = $('#id_ubigeo')
      distrito.html('');
      $.ajax({
            'url': '{% url "ubigeo:api_distritos" %}' + '?provincia=' + provincia,
            'method': 'GET',
            'success': function (data) {
                distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
                for (var i = 0; i < data.distritos.length; i++) {
                  if (code_distrito == data.distritos[i].pk) {
                    distrito.append('<option selected="selected" value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  } else {
                    distrito.append('<option value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  }
                }
                code_distrito = ''
                // provincia.change();
            }
        })


    });
  });
</script>
{% endblock js %}

src/templates/pages/complaints_book_generate.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class="boxw pages">
        <div class="w-body">
          <h2 class='pages__title'>Libro de reclamaciones</h2>
          <form class="pages__content" method="POST" action=".">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-10 col-md-offset-1">
                <h3 class="w-body__title">1. IDENTIFICACIÓN DEL CONSUMIDOR RECLAMANTE</h3>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Nombres</label>
                      <p>{{complaints.first_name}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Apellidos</label>
                      <p>{{complaints.last_name}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Email</label>
                      <p>{{complaints.email}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Celular</label>
                      <p>{{complaints.phone}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Tipo de documento</label>
                      <p>{{complaints.type_document}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Documento</label>
                      <p>{{complaints.document}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Departamento / Provincia / Distrito</label>
                      <p>{{complaints.ubigeo.full_ubigeo}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Dirección</label>
                      <p>{{complaints.address}}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 col-md-offset-1">
                <br></br>
                <h3 class="w-body__title">2. IDENTIFICACIÓN DEL BIEN CONTRATADO</h3>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Tipo de bien contratado</label>
                      <p>{{complaints.get_well_contracted_display}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Monto</label>
                      {% if complaints.mount %}
                        <p>{{complaints.mount}}</p>
                      {% else %}
                          <p></p>
                      {% endif %}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Número de pedido</label>
                      <p>{{complaints.pedido}}</p>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Descripción</label>
                      <p>{{complaints.desciption}}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 col-md-offset-1">
                <br></br>
                <h3 class="w-body__title">3. DETALLE DE LA RECLAMACIÓN Y PEDIDO DEL CONSUMIDOR</h3>
                <div class="row">
                  <div class="col-md-12">
                    <p>Reclamo: Disconformidad relacionada a los productos o servicios.</p>
                  </div>
                  <div class="col-md-12">
                    <p>Queja: Disconformidad no relacionada a los productos o servicios; o malestar o descontento respecto a la atención al público.</p>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Tipo de bien contratado</label>
                      <p>{{complaints.get_type_claim_display}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Pedido del consumidor</label>
                      <p>{{complaints.consumers_order}}</p>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="">Detalle del reclamo</label>
                      <p>{{complaints.detail}}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-10 col-md-offset-1">
                <br></br>
                <h3 class="w-body__title">4. OBSERVACIONES Y ACCIONES ADOPTADAS POR EL PROVEEDOR</h3>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="">Descripción</label>
                      <p>{{complaints.observation}}</p>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <button class='btn btn-primary btn-lg'>Imprimir</button>
                  </div>
                </div>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/contact.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class=" pages">
        <div class="w-body">
          <h2 class='preguntas_frecuentes__title'>Contacto</h2>
          <form class="pages__content" method="POST" action=".">
            {% csrf_token %}
            <div class="row">

              <div class="col-md-8 ">
                <div class="row">
                  <div class="col-md-12">
                    <p>Si tienes alguna consulta, podras contactarnos mediante este formulario. </p>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      {{form.first_name.label_tag}}
                      {{form.first_name|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      {{form.last_name.label_tag}}
                      {{form.last_name|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      {{form.email.label_tag}}
                      {{form.email|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      {{form.subject.label_tag}}
                      {{form.subject|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      {{form.phone.label_tag}}
                      {{form.phone|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      {{form.message.label_tag}}
                      {{form.message|add_class:'form-control'}}
                    </div>
                  </div>
                  <div class="col-md-12">
                    <button class='btn btn--dark pull-right'>Enviar</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/contact_thanks.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class="boxw pages">
        <div class="w-body">
          <h2 class='pages__title'>Contacto</h2>
          <div class="pages__content">

            <div class="row">

              <div class="col-md-8 col-md-offset-2">
                <div class="row">
                  <div class="col-md-12">
                    <p>Gracias por contactarnos, un ejecutivo se contactara con ustedes</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/frequent_question.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class="boxw pages">
        <div class="w-body">
          <h2 class='pages__title'>Preguntas Frecuentes</h2>
          <div class="pages__content">
            {{frequent_question.content|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/page.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout preguntas_frecuentes">
  <div class="container">
    <div class="row ">
      <div class="col-xs-12">
        <div class="w-body">
          <h2 class='preguntas_frecuentes__title'>{{page.name|safe}}</h2>
          <div class="pages__content">
            {{page.description|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/payment_methods.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class="boxw pages">
        <div class="w-body">
          <h2 class='pages__title'>Formas de Pago</h2>
          <div class="pages__content">
            {{payment.content|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/question_response.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout preguntas_frecuentes">
  <div class="container">
    <div class="preguntas_frecuentes__row">
      <div class="preguntas_frecuentes__row__col_block1">
        <h3 class="preguntas_frecuentes__title">
          {{question_response_first.question}}
        </h3>
      </div>
    </div>
    <div class="preguntas_frecuentes__row ">
      <div class="preguntas_frecuentes__row__col_block1">
        <div class="w-body">
          <div class="pages__content">
            {{question_response_first.content|safe}}
          </div>
        </div>
      </div>
      <div class="preguntas_frecuentes__row__col_block2">
        <div class="">
          <div class="w-body">
            <div class="sidebar sidebar_account">
            <ul class='preguntas_frecuentes__sidebar'>
              {% for question_response in question_responses %}
                <li><a href="{% url 'web_page:question_response_question' question_response.slug %}">{{question_response.question}}
                   </a></li>
              {% endfor %}
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/question_response_question.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout preguntas_frecuentes">
  <div class="container">
    <div class="preguntas_frecuentes__row">
      <div class="preguntas_frecuentes__row__col_block1">
        <h3 class="preguntas_frecuentes__title">
          {{question_response.question}}
        </h3>
      </div>
    </div>
    <div class="preguntas_frecuentes__row ">
      <div class="preguntas_frecuentes__row__col_block1">
        <div class="w-body">
          <div class="pages__content">
            {{question_response.content|safe}}
          </div>
        </div>
      </div>
      <div class="preguntas_frecuentes__row__col_block2">
        <div class="">
          <div class="w-body">
            <div class="sidebar sidebar_account">
            <ul class='preguntas_frecuentes__sidebar'>
              {% for question in question_responses %}
                <li><a {% if question_response.slug == question.slug %}class='active'{% endif %} href="{% url 'web_page:question_response_question' question.slug %}">{{question.question}}
                   </a></li>
              {% endfor %}
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/pages/terms_conditions.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row ">
      <div class="boxw pages">
        <div class="w-body">
          <h2 class='pages__title'>Terminos y Condiciones</h2>
          <div class="pages__content">
            {{terms.content|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}