src/apps_base/order/urls.py
from django.conf.urls import url
from rest_framework import routers
from .views import (OrderViewSet, OrderDashboardHeaderAPI, OrderDashboardSalesAPI,
    OrderDashboardCountAPI, OrderDashboardFooterAPI)

router = routers.SimpleRouter()
router.register(r'order', OrderViewSet)

urlpatterns = [
    url(r"^order-dashboard-header/$", OrderDashboardHeaderAPI.as_view()),
    url(r"^order-dashboard-footer/$", OrderDashboardFooterAPI.as_view()),
    url(r"^order-dashboard-sales/$", OrderDashboardSalesAPI.as_view()),
    url(r"^order-dashboard-count/$", OrderDashboardCountAPI.as_view()),
]

urlpatterns += router.urls

src/apps_web/web_cart/urls.py
from django.conf.urls import url
from .api_views import CartAPI
from .views import cart


urlpatterns = [
    url(r"^api/cart/$", CartAPI.as_view(), name="cart_api"),

    url(r"^carro-compras/$", cart, name="cart"),
]

src/apps_web/web_order/urls.py
from django.conf.urls import url
from .views import (checkout_paso_1, checkout_paso_2, checkout_thanks,
    get_price_shipping, get_coupon_discount, checkout_new)
from .api_views import (InfluencerShippingProductAPI, CustomerShippingAddressAPI, CustomerAPI,
    CustomerShippingAddressUpdateAPI)

urlpatterns = [
    url(r"^checkout/paso-1/$", checkout_paso_1, name="checkout_paso_1"),
    url(r"^checkout/paso-2/$", checkout_paso_2, name="checkout_paso_2"),
    url(r"^proceso-compra/paso-1/$", checkout_new, name="checkout_new"),
    url(r"^proceso-compra/paso-2/$", checkout_new, name="checkout_new_2"),
    url(r"^proceso-compra/paso-3/$", checkout_new, name="checkout_new_3"),
    url(r"^proceso-compra/gracias/$", checkout_thanks, name="checkout_thanks"),
    url(r"^ubigeo-price/$", get_price_shipping, name="get_price_shipping"),
    url(r"^validate-coupon/$", get_coupon_discount, name="get_coupon_discount"),
    url(r"^customer-shipping-address/$",
        CustomerShippingAddressAPI.as_view(),
        name="customer_shipping_address"),
    url(r"^customer-shipping-address/(?P<pk>\d+)/$",
        CustomerShippingAddressUpdateAPI.as_view(),
        name="customer_shipping_address_update"),
    url(r"^api/influencer-shipping-product/$",
        InfluencerShippingProductAPI.as_view(),
        name="influencer_shipping_product"),
    url(r"^api/order-customer/$",
        CustomerAPI.as_view())
]

src/apps_web/web_system/urls.py
from django.conf.urls import url
from .views import (home, login_register, account, test_email,
    logout_view, my_address, my_address_edit, my_order, my_order_detail, my_address_create,
    follow_orders, testing_view, create_account)
from .api_views import SuscriptionAPI

urlpatterns = [
    url(r"^$", home, name="home"),
    url(r"^ingresar/$", login_register, name="login_register"),
    url(r"^crear-cuenta/$", create_account, name="create_account"),
    url(r"^mi-cuenta/$", account, name="account"),
    url(r"^mis-direcciones/$", my_address, name="my_address"),
    url(r"^mis-direcciones/(?P<pk>\d+)/$", my_address_edit, name="my_address_edit"),
    url(r"^test-email/$", test_email, name="test_email"),
    url(r"^salir/$", logout_view, name="logout_view"),
    url(r"^mis-ordenes/$", my_order, name="my_order"),
    url(r"^mis-direcciones/crear/$", my_address_create, name="my_address_create"),
    url(r"^mis-ordenes/(?P<pk>\d+)/$", my_order_detail, name="my_order_detail"),
    url(r"^sigue-orden/$", follow_orders, name="follow_orders"),
    url(r"^testing_view/$", testing_view, name="testing_view"),
    url(r"^api-suscripcion/$", SuscriptionAPI.as_view(), name="api_suscripcion"),
]

src/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]  + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    url(r'^api-v1/', include([
        url(r'security/',
            include('apps_base.security.urls', namespace='security')),
        url(r'influencer/',
            include('apps_base.influencer.urls', namespace='influencer')),
        url(r'category/',
            include('apps_base.category.urls', namespace='category')),
        url(r'product/',
            include('apps_base.product.urls', namespace='product')),
        url(r'family/',
                include('apps_base.family.urls', namespace='family')),
        url(r'attribute/',
            include('apps_base.attribute.urls', namespace='attribute')),
        url(r'pages/',
            include('apps_base.pages.urls', namespace='pages')),
        url(r'form/',
            include('apps_base.form.urls', namespace='form')),
        url(r'ubigeo/', include('apps_base.ubigeo.urls', namespace='ubigeo')),
        url(r'payment/', include('apps_base.payment.urls', namespace='payment')),
        url(r'customers/', include('apps_base.customers.urls', namespace='customers')),
        url(r'order/', include('apps_base.order.urls', namespace='order')),
        url(r'configuration/', include('apps_base.configuration.urls', namespace='configuration')),
        url(r'shipping/', include('apps_base.shipping.urls', namespace='shipping')),
        url(r'promotion/', include('apps_base.promotion.urls', namespace='promotion')),
        url(r'custom_auth/', include('apps_base.custom_auth.urls', namespace='custom_auth'))
    ])),
    url(r'^api-influencer/', include('admin_influencer.urls', namespace='admin_influencer')),
    url(r'^', include('apps_web.web_system.urls', namespace='web_system')),
    url(r'^', include('apps_web.web_product.urls', namespace='web_product')),
    url(r'^', include('apps_web.web_cart.urls', namespace='web_cart')),
    url(r'^', include('apps_web.web_order.urls', namespace='web_order')),
    url(r'^', include('apps_web.web_page.urls', namespace='web_page')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps_base/order/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _
from .constants import TYPE_STATUS, TYPE_STATUS_SHIPPING, ALMACEN
from .utils import generate_code_order
from apps_base.customers.constants import TYPE_DOCUMENT_CHOICES
from apps_base.core.models import CoreTimeModel, CoreActiveModel


class Order(CoreTimeModel, CoreActiveModel):
    customer = models.ForeignKey(
        'customers.Customer', related_name="customer_orders")
    cart = models.OneToOneField(
        'cart.Cart', related_name="cart_order", null=True, blank=True
    )
    code = models.CharField("code", max_length=255, unique=True)
    sub_total = models.DecimalField("sub total", decimal_places=2, max_digits=8)
    shipping_price = models.DecimalField("Envio", decimal_places=2, max_digits=8, default=0)
    discount = models.DecimalField("Descuento", decimal_places=2, max_digits=8, default=0)
    # coupon = models.OneToOneField('promotion.CouponGenerate', related_name='coupon_order', blank=True, null=True)
    coupon_discount = models.ForeignKey('promotion.Coupon', related_name='coupon_orders', blank=True, null=True)
    total = models.DecimalField("total", decimal_places=2, max_digits=8)
    type_status = models.CharField(
        "type_status", choices=TYPE_STATUS, max_length=255, blank=True)
    type_status_shipping = models.CharField(
        "type status shipping", choices=TYPE_STATUS_SHIPPING, max_length=255, default=ALMACEN)
    is_send_email = models.BooleanField(default=False)
    is_return_stock = models.BooleanField(default=False)
    extra_data = JSONField(default={}, blank=True)
    discount_stock = models.BooleanField(default=False)
    shipping_influencer = JSONField(default={}, blank=True)

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Order"
        permissions = (
            ('can_list_order', 'Order List'),
            ('can_read_order', 'Order Read List'),
        )


    def save(self, *args, **kwargs):
        if not self.code:
            self.code = generate_code_order()
        super(Order, self).save(*args, **kwargs)

    def update_total(self):
        self.sub_total = self.cart.total
        self.total = self.cart.total + self.shipping_price - self.discount
        self.save()

    def __str__(self):
        return '{}'.format(self.code)


class OrderDetail(models.Model):
    order = models.ForeignKey(
        "Order", related_name="order_orderdetail"
    )
    productdetail = models.ForeignKey(
        'product.Product', related_name="product_orderdetails"
    )
    quantity = models.IntegerField()
    price = models.DecimalField("price", decimal_places=2, max_digits=8)
    sub_total = models.DecimalField("sub_total", default=0, decimal_places=2, max_digits=8)
    total = models.DecimalField("total", decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = "OrderDetail"
        verbose_name_plural = "OrderDetail"
        unique_together = ('order', 'productdetail',)


class OrderCustomer(models.Model):
    order = models.OneToOneField(
        "Order", related_name="order_order_customer"
    )
    first_name = models.CharField(_('Name'), max_length=255)
    last_name = models.CharField(_('last name'), max_length=255)
    email = models.EmailField("Email")
    phone = models.CharField("Celular", max_length=120, blank=True)
    document = models.CharField("Documento", blank=True, max_length=120)
    type_document = models.CharField(
        "Tipo Documento", blank=True, choices=TYPE_DOCUMENT_CHOICES, max_length=120)

    class Meta:
        verbose_name = "OrderCustomer"
        verbose_name_plural = "OrderCustomer"

    def get_full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __str__(self):
        return '{}'.format(self.first_name)

class OrderShippingCostInfluencer(models.Model):
    order = models.ForeignKey(
        "Order", related_name="order_shipping_cost_influencers", on_delete=models.CASCADE
    )
    influencer = models.ForeignKey(
        'influencer.Influencer', related_name='order_influencers', on_delete=models.CASCADE)
    price = models.FloatField()
    date = models.DateField()
    shipping_cost = models.ForeignKey(
        'shipping.ShippingCost', related_name='order_shipping_costs', on_delete=models.CASCADE)
    class Meta:
        verbose_name = "OrderShippingInfluencer"
        verbose_name_plural = "OrderShippingInfluencers"
        unique_together = ('order', 'influencer')

    def __str__(self):
        return 'shippingOrder'


class OrderShippingAddress(models.Model):
    order = models.OneToOneField(
        "Order", related_name="order_ordershipping"
    )
    first_name = models.CharField(_('Name'), max_length=255)
    last_name = models.CharField(_('last name'), max_length=255)
    address = models.CharField("Dirección", max_length=255)
    reference = models.CharField("Referencia", max_length=255, blank=True)
    ubigeo = models.ForeignKey("ubigeo.Ubigeo", related_name='ubigeo_order_shipping_address')
    document = models.CharField("Documento", blank=True, max_length=120)
    type_document = models.CharField(
        "Tipo Documento", blank=True, choices=TYPE_DOCUMENT_CHOICES, max_length=120)
    phone = models.CharField("Celular", max_length=120)
    shipping_address = models.ForeignKey("customers.CustomerShippingAddress", null=True, blank=True)

    class Meta:
        verbose_name = "OrderShipping"
        verbose_name_plural = "OrderShipping"

    def __str__(self):
        return '{}'.format(self.first_name)

    def get_full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

src/templates/order/checkout_2.html
{% extends "common/base_order.html" %}
{% load static thumbnail widget_tweaks l10n %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/cart.min.css' %}">
{% endblock css %}
{% block content %}
<section class="main checkout">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="row">
          <div class="col-md-12">
            <div class="boxw">
              <div class="w-body">
                <h3 class="w-body__title">Resumen Información de Contacto</h3>
                <form class="form-horizontal form-checkout form-checkout-1" action="" method='POST'>

                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Email</label>:
                      <span>{{order_customer.email}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Telefono:</label>
                      <span>{{order_customer.phone}}</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Nombres:</label>
                      <span>{{order_customer.first_name}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Apellidos:</label>
                      <span>{{order_customer.last_name}}</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Tipo Documento:</label>
                      <span>{{order_customer.get_type_document_display}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Documento:</label>
                      <span>{{order_customer.document}}</span>
                    </div>
                  </div>


                </form>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="boxw">
              <div class="w-body">
                <h3 class="w-body__title">Resumen Dirección de Envío</h3>
                <form class="form-horizontal form-checkout form-checkout-1" action="" method='POST'>
                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Nombres:</label>
                      <span>{{order_shipping.first_name}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Apellidos:</label>
                      <span>{{order_shipping.last_name}}</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Tipo Documento:</label>
                      <span>{{order_shipping.get_type_document_display}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Documento:</label>
                      <span>{{order_shipping.document}}</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Telefono:</label>
                      <span>{{order_shipping.phone}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Zona:</label>
                      <span>{{order_shipping.ubigeo.full_ubigeo}}</span>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-xs-6">
                      <label for="">Dirección:</label>
                      <span>{{order_shipping.address}}</span>
                    </div>
                    <div class="col-xs-6">
                      <label for="">Referencia:</label>
                      <span>{{order_shipping.reference}}</span>
                    </div>
                  </div>



                </form>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="boxw">
              <div class="w-body">
                <h3 class="w-body__title">
                  Metodo De Pago
                </h3>
                <form action="" method="POST" class=' form-horizontal form-checkout form-checkout-1' id="culqi-card-form">
                    <div data-capture-name="true" class='card-js' id="my-card">
                      <div class="form-group">
                          <div class="col-md-12">
                            <label>
                             <span>Correo Electrónico</span>
                            </label>
                            <input type="text" size="50" id="card[email]" name="card-holders-name" placeholder="Correo Electrónico" class="name form-control" data-culqi="card[email]">
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-md-4">
                            <label>
                             <span>Número de tarjeta</span>
                            </label>
                            <input type="text" size="20" name="card-number" name="card-number" placeholder="Número de Tarjeta" class="card-number my-custom-class form-control" data-culqi="card[number]" id="card[number]">
                          </div>
                          <div class="col-md-5">
                            <label>
                             Fecha expiración (MM/YYYY)
                            </label>
                            <input type="hidden" size="2" class="expiry-month form-control"  data-culqi="card[exp_month]" id="card[exp_month]">
                            <input type="hidden" size="4" class="expiry-year form-control" data-culqi='card[exp_year]' id='card[exp_year]'>
                          </div>
                          <div class="col-md-3">
                            <label>
                              <span>CVC</span>
                            </label>
                            <input type="text" size="4" name='cvc' class="cvc form-control" data-culqi='card[cvv]' id='card[cvv]'>
                          </div>
                      </div>
                    </div>
                    <div class="col-xs-12">
                      <div class="form-group">
                        <label for="">
                          <input type="checkbox" id='terminos_condiciones'> <a href="/terminos-condiciones" target='_blank'>Acepto terminos y condiciones</a>
                        </label>
                      </div>
                    </div>

                  <div class="form-group">
                    <div class="col-md-12">
                        <div class="w-lnk-btn"><a href="{% url 'web_order:checkout_paso_1' %}" class="lnk"><i class="fa fa-angle-left"></i>Regresar</a>
                        <button type="submit" id="pagar" disabled="disabled" class="btn btn-primary">Pagar</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="boxw">
          <div class="box-items">

          {% for detail in order_details %}

            <div class="item-car">
              <div class="item">
                <div class="image">
                  {% thumbnail detail.productdetail.get_image "60x60" crop="center" as im %}
                    <img src="{{ im.url }}"  height="{{ im.height }}">
                  {% endthumbnail %}
                </div>
              </div>
              <div class="detail">
                <h3>{{detail.productdetail.product_class.name}}</h3>
                <div class="sizes">Medium</div>
              </div>
            </div>
          {% endfor %}

          </div>
          <div class="totals">
            <div class="subtotal"> <span class="title-s">Subtotal: </span><strong>S/. <span class='subTotal'> {{order.sub_total|unlocalize}}</span>               </strong></div>
            <div class="subtotal"> <span class="title-s">Descuento: </span><strong>S/. <span class='descuento'> {{order.discount|unlocalize}}</span>               </strong></div>
            <div class="subtotal"> <span class="title-s">Costo envio: </span><strong>S/. <span class='shipping_price'>
                {{order.shipping_price|unlocalize}}
              </span></strong>
            </div>
            <div class="total">
              <span class="title-s">Total: </span>
              <strong>S/.
                <span class='totalPrice'>
                  {{order.total|unlocalize}}
                </span></strong>
            </div>
            <!--<div class="total"><span class="to">Total:   </span><strong>S/. {{cart.total}}</strong></div>-->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div id="modal-container">
  <div class="modal-background">
    <div class="modal">
      <h4 class='procesando'>Procesando su Pago</h4>
      <img src="{% static 'img/culqi_logo.png' %}" alt="" class='logo_culqui'>
      <svg class="modal-svg" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" preserveAspectRatio="none">
                <rect x="0" y="0" fill="none" width="100%" height="100%" rx="3" ry="3"></rect>
              </svg>
    </div>
  </div>
</div>
{% endblock content %}
{% block js %}
  <script src="https://checkout.culqi.com/v2"></script>
  <script src="{% static 'js/cartjs.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <script src="{% static 'js/csrfcookie.js' %}"></script>
  <script>
    Culqi.publicKey = '{{CULQUI_PUBLIC_KEY_TEST}}';
    Culqi.init();

    function culqi() {
      if(Culqi.token) { // ¡Token creado exitosamente!
          // Get the token ID:
          var data = Culqi.token;

          $.ajax({
            url: '{% url "payment:save_token" %}',
            type: 'POST',
            data: {'token': JSON.stringify(data)}
          }).done(function (data) {
            if (data.status === 'ok') {
              $('.procesando').text('Se proceso su pago ')
              setTimeout(function(){
                 window.location.href = '{% url "web_order:checkout_thanks" %}'
              }, 1000);

            } else {
              $('.procesando').text(data.msg)
              if (data.type_error == 'STOCK') {
                setTimeout(function(){
                 window.location.href = '{% url "web_cart:cart" %}'
                }, 1000);
              }
              console.log(data)
            }
          })

      }else{ // ¡Hubo algún problema!
          // Mostramos JSON de objeto error en consola

          var data = Culqi.error
          $('.procesando').text(data.user_message)
          console.log(data)
      }
    };
    $("#terminos_condiciones").change(function(event) {
      if ($("input[name='card-number']").val() && $("input[name='card-holders-name']").val() && $("input[name='cvc']").val() && $("input.expiry-year").val() && $("input.expiry-month").val() && $("#terminos_condiciones").is(":checked")) {
        $('#pagar').removeAttr('disabled')
      } else {
        $('#pagar').attr('disabled', 'disabled')
      }
    });
    $("#culqi-card-form input").keyup(function(event) {
      /* Act on the event */
      console.log('entro')
      if ($("input[name='card-number']").val() && $("input[name='card-holders-name']").val() && $("input[name='cvc']").val() && $("input.expiry-year").val() && $("input.expiry-month").val() && $("#terminos_condiciones").is(":checked")) {
        $('#pagar').removeAttr('disabled')
      } else {
        $('#pagar').attr('disabled', 'disabled')
      }
    });

    $('#pagar').click(function(event) {
      event.preventDefault()
      $('#modal-container').removeAttr('class').addClass('six');
      $('body').addClass('modal-active');
      $('.procesando').text('Procesando su Pago')
      Culqi.createToken();
    });
    $('#modal-container').click(function(){
      $(this).addClass('out');
      $('body').removeClass('modal-active');
    });
    jQuery(document).ready(function($) {
      var myCard = $('#my-card');
      // myCard.CardJs.NAME_PLACEHOLDER = 'Email';
    });
</script>
{% endblock js %}

src/templates/order/checkout_new_1.html
{% extends "common/base_order.html" %}
{% load static thumbnail widget_tweaks l10n %}
{% block css %}

{% endblock css %}
{% block content %}
<div class="content-loader">
  <div class="loader">
  </div>
</div>
<router-view ></router-view>
{% endblock content %}
{% block before_js %}
  <script src="https://checkout.culqi.com/v2"></script>
  <script>
  var publicKey = '{{CULQUI_PUBLIC_KEY_TEST}}'
  var static_logo = '{% static "img/culqi_logo.png" %}'
  // var culquihtml = Culqi
    // function culqi() {
    //     if(Culqi.token) { // ¡Token creado exitosamente!
    //       // Get the token ID:
    //         var data = Culqi.token;
    //         console.log(data, 'dataex')
    //     } else { // ¡Hubo algún problema!
    //           // Mostramos JSON de objeto error en consola

    //         var data = Culqi.error
    //         console.log(data, 'dataex')
    //       }
    // }
  // Culqi.publicKey = publicKey
  // Culqi.init();
  </script>
{% endblock before_js %}
{% block js %}
    <script>
    jQuery(document).ready(function($) {

    });

    $(window).load(function() {
        $( ".content-loader" ).fadeOut(1000)
    });

    </script>
{% endblock js %}

src/templates/order/checkout_thanks.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main main_checkout_thanks">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="boxw box-car">
          <div class="inner text-center">
            <h3 class="main_checkout_thanks__title">¡Gracias por tu compra!</h3>
            <p class="main_checkout_thanks__description">El número de su pedido es: {{order.code}}</p>
            <p class="main_checkout_thanks__description">El número de su cargo es: {{order.extra_data.id_charge}}</p>
            <p class="main_checkout_thanks__description"> Te enviaremos un correo confirmando tu compra.</p>
            <a href="{% url 'web_system:home' %}" class="btn btn-primary">Volver al Home</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}