src/apps_base/ubigeo/urls.py
from django.conf.urls import url
from .views import departamentos, provincias, distritos, ubigeo_full_name

urlpatterns = [
    url(r'^departamentos/$', departamentos, name='api_departamentos'),
    url(r'^provincias/$', provincias, name='api_provincias'),
    url(r'^distritos/$', distritos, name='api_distritos'),
    url(r'^ubigeo-full-name/$', ubigeo_full_name, name='ubigeo_full_name'),
]

src/apps_web/web_system/urls.py
from django.conf.urls import url
from .views import (home, login_register, account, test_email,
    logout_view, my_address, my_address_edit, my_order, my_order_detail, my_address_create,
    follow_orders, testing_view, create_account)
from .api_views import SuscriptionAPI

urlpatterns = [
    url(r"^$", home, name="home"),
    url(r"^ingresar/$", login_register, name="login_register"),
    url(r"^crear-cuenta/$", create_account, name="create_account"),
    url(r"^mi-cuenta/$", account, name="account"),
    url(r"^mis-direcciones/$", my_address, name="my_address"),
    url(r"^mis-direcciones/(?P<pk>\d+)/$", my_address_edit, name="my_address_edit"),
    url(r"^test-email/$", test_email, name="test_email"),
    url(r"^salir/$", logout_view, name="logout_view"),
    url(r"^mis-ordenes/$", my_order, name="my_order"),
    url(r"^mis-direcciones/crear/$", my_address_create, name="my_address_create"),
    url(r"^mis-ordenes/(?P<pk>\d+)/$", my_order_detail, name="my_order_detail"),
    url(r"^sigue-orden/$", follow_orders, name="follow_orders"),
    url(r"^testing_view/$", testing_view, name="testing_view"),
    url(r"^api-suscripcion/$", SuscriptionAPI.as_view(), name="api_suscripcion"),
]

src/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]  + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    url(r'^api-v1/', include([
        url(r'security/',
            include('apps_base.security.urls', namespace='security')),
        url(r'influencer/',
            include('apps_base.influencer.urls', namespace='influencer')),
        url(r'category/',
            include('apps_base.category.urls', namespace='category')),
        url(r'product/',
            include('apps_base.product.urls', namespace='product')),
        url(r'family/',
                include('apps_base.family.urls', namespace='family')),
        url(r'attribute/',
            include('apps_base.attribute.urls', namespace='attribute')),
        url(r'pages/',
            include('apps_base.pages.urls', namespace='pages')),
        url(r'form/',
            include('apps_base.form.urls', namespace='form')),
        url(r'ubigeo/', include('apps_base.ubigeo.urls', namespace='ubigeo')),
        url(r'payment/', include('apps_base.payment.urls', namespace='payment')),
        url(r'customers/', include('apps_base.customers.urls', namespace='customers')),
        url(r'order/', include('apps_base.order.urls', namespace='order')),
        url(r'configuration/', include('apps_base.configuration.urls', namespace='configuration')),
        url(r'shipping/', include('apps_base.shipping.urls', namespace='shipping')),
        url(r'promotion/', include('apps_base.promotion.urls', namespace='promotion')),
        url(r'custom_auth/', include('apps_base.custom_auth.urls', namespace='custom_auth'))
    ])),
    url(r'^api-influencer/', include('admin_influencer.urls', namespace='admin_influencer')),
    url(r'^', include('apps_web.web_system.urls', namespace='web_system')),
    url(r'^', include('apps_web.web_product.urls', namespace='web_product')),
    url(r'^', include('apps_web.web_cart.urls', namespace='web_cart')),
    url(r'^', include('apps_web.web_order.urls', namespace='web_order')),
    url(r'^', include('apps_web.web_page.urls', namespace='web_page')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/templates/system/account.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main page-account">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="">
          <h2 class='page_account__title'>Información Personal</h2>
          <div class="pages__content">
            <div class="row">

              <div class="col-md-12">
                <form action="" method='POST' class='page-account__form'>
                  {% csrf_token %}
                  <div class="row form-group">
                    <div class="col-md-6">
                      {{form_user.first_name|add_class:'form-control'|attr:'placeholder:Nombres'}}
                      <p class='text-danger'>{{form_user.first_name.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_user.last_name|add_class:'form-control'|attr:'placeholder:Apellidos'}}
                      <p class='text-danger'>{{form_user.last_name.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_user.email|add_class:'form-control'|attr:'placeholder:Email'}}
                      <p class='text-danger'>{{form_user.email.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_customer.type_document|add_class:'form-control'|attr:'placeholder:Tipo de Documento'}}
                      <p class='text-danger'>{{form_user.type_document.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_customer.document|add_class:'form-control'|attr:'placeholder:Documento'}}
                      <p class='text-danger'>{{form_user.document.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_customer.gender|add_class:'form-control'|attr:'placeholder:Genero'}}
                      <p class='text-danger'>{{form_user.gender.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form_customer.phone|add_class:'form-control'|attr:'placeholder:Teléfono'}}
                      <p class='text-danger'>{{form_user.phone.errors}}</p>
                    </div>

                  </div>
                  <div class="row">
                      <div class="col-md-12">
                        <button class='btn btn--dark pull-right'>Guardar</button>
                      </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 ">
        <div class="w-body">
          <div class="sidebar sidebar_account">
            <ul class='preguntas_frecuentes__sidebar preguntas_frecuentes__sidebar--account'>
              <li ><a href="{% url 'web_system:account' %}" class='active'>Información Personal
                 </a></li>
              <li><a href="{% url 'web_system:my_address' %}">Mis direcciones</a></li>
              <li><a href="{% url 'web_system:my_order' %}">Mis Ordenes</a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}

src/templates/system/my_address.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main page-account page_account">
  <div class="container">
    <div class="row">

      <div class="col-md-9">
        <div class="">
          <h2 class='page_account__title'>MIS DIRECCIONES</h2>
          <div class=" pages__content">
            <div class="row">

              {% for add in address %}
              <div class="col-md-12 ">
                <div class=" content_address content_address__flex">
                  <a href='{% url "web_system:my_address_edit" add.pk %}' class="">
                    <strong>{{add.get_type_address_display}}</strong>
                    <p>{{add.address}} - {{add.ubigeo.full_ubigeo}}</p>
                  </a>
                  <a href="" class='content_address__trash'>
                    <i class='fa fa-trash'></i>
                  </a>
                </div>
              </div>
                {% endfor %}
            </div>
            <div class="row">
              <div class="col-md-12">
                <a href='{% url "web_system:my_address_create" %}' class="btn btn--dark pull-right">Agregar Dirección</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 ">
        <div class="w-body">
          <div class="sidebar sidebar_account">
            <ul class='preguntas_frecuentes__sidebar preguntas_frecuentes__sidebar--account'>
              <li><a href="{% url 'web_system:account' %}">Información Personal
                 </a></li>
              <li><a class='active' href="{% url 'web_system:my_address' %}">Mis direcciones</a></li>
              <li><a href="{% url 'web_system:my_order' %}">Mis Ordenes</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}
<script>
  jQuery(document).ready(function($) {
    var departamento_initial = $('#id_shipping-departamento')
    departamento_initial.html('')
    var code_departamento = '{{code_departamento}}'
    var code_provincia = '{{code_provincia}}'
    var code_distrito = '{{code_distrito}}'
    $.ajax({
        'url': '{% url "ubigeo:api_departamentos" %}',
        'method': 'GET',
        'success': function (data) {
            departamento_initial.append('<option value="" selected="selected">Seleccione Departamento</option>');
            for (var i = 0; i < data.departamentos.length; i++) {
              if (code_departamento == data.departamentos[i].codigo) {
                departamento_initial.append('<option selected="selected" value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              } else {
                departamento_initial.append('<option value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              }
            }
            if (code_departamento) {
              $('#id_shipping-departamento').trigger('change')
            }
            // provincia.change();
        }
    })
    $('#id_shipping-departamento').change(function(event) {
    /* Act on the event */
      var departamento = $(this).val();
      var provincia = $('#id_shipping-provincia')
      var distrito = $('#id_shipping-ubigeo')
      provincia.html('');
      distrito.html('');
      if (departamento) {
        $.ajax({
              'url': '{% url "ubigeo:api_provincias" %}' + '?departamento=' + departamento,
              'method': 'GET',
              'success': function (data) {
                  provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
                  for (var i = 0; i < data.provincias.length; i++) {
                    if (code_provincia == data.provincias[i].codigo) {
                      provincia.append('<option  selected="selected" value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    } else {
                      provincia.append('<option value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    }
                  }
                  if (code_provincia) {
                    $('#id_shipping-provincia').trigger('change')
                  }
                  // provincia.change();
              }
          })
      } else {
        provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
        distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
        code_provincia = ''
      }


    });
    $('#id_shipping-provincia').change(function(event) {
    /* Act on the event */
      var provincia = $(this).val();
      var distrito = $('#id_shipping-ubigeo')
      distrito.html('');
      $.ajax({
            'url': '{% url "ubigeo:api_distritos" %}' + '?provincia=' + provincia,
            'method': 'GET',
            'success': function (data) {
                distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
                for (var i = 0; i < data.distritos.length; i++) {
                  if (code_distrito == data.distritos[i].pk) {
                    distrito.append('<option selected="selected" value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  } else {
                    distrito.append('<option value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  }
                }
                code_distrito = ''
                // provincia.change();
            }
        })


    });
  });
</script>
{% endblock js %}

src/templates/system/my_address_create.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main page-account">
  <div class="container">
    <div class="row">

      <div class="col-md-10 col-md-offset-1">
        <div class="">
          <div class="page_account__title">
            Mi dirección
          </div>
          <div class="w-body">
            <div class="row">
              <div class="col-md-12">
                <form action="" method='POST' class='page-account__form'>
                  {% csrf_token %}
                  <div class="row form-group">
                    <div class="col-md-6">
                      {{form.first_name.label_tag}}
                      {{form.first_name|add_class:'form-control'}}
                      <p class='text-danger'>{{form.first_name.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.last_name.label_tag}}
                      {{form.last_name|add_class:'form-control'}}
                      <p class='text-danger'>{{form.last_name.errors}}</p>
                    </div>

                    <div class="col-md-6">
                      {{form.type_document.label_tag}}
                      {{form.type_document|add_class:'form-control'}}
                      <p class='text-danger'>{{form.email.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.document.label_tag}}
                      {{form.document|add_class:'form-control'}}
                      <p class='text-danger'>{{form.document.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.phone.label_tag}}
                      {{form.phone|add_class:'form-control'}}
                      <p class='text-danger'>{{form.phone.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.address.label_tag}}
                      {{form.address|add_class:'form-control'}}
                      <p class='text-danger'>{{form.address.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.reference.label_tag}}
                      {{form.reference|add_class:'form-control'}}
                      <p class='text-danger'>{{form.reference.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.type_address.label_tag}}
                      {{form.type_address|add_class:'form-control'}}
                      <p class='text-danger'>{{form.type_address.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Departamento</label>
                      <select class="form-control" id='id_shipping-departamento'
                      name="departamento" >
                        <option value="">Seleccione Departamento</option>
                      </select>
                      <p></p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Provincia</label>
                      <select class="form-control" name="provincia" id="id_shipping-provincia">
                        <option value="">Seleccione Provincia</option>
                      </select>
                      <p></p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Distrito</label>
                      {{form.ubigeo|add_class:'form-control'}}
                      <p class='text-danger'>{{form.ubigeo.errors}}</p>
                    </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                         <button class='btn btn--dark pull-right'>Guardar</button>
                      </div>
                  </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}
<script>
  jQuery(document).ready(function($) {
    var departamento_initial = $('#id_shipping-departamento')
    departamento_initial.html('')
    var code_departamento = '{{code_departamento}}'
    var code_provincia = '{{code_provincia}}'
    var code_distrito = '{{code_distrito}}'
    $.ajax({
        'url': '{% url "ubigeo:api_departamentos" %}',
        'method': 'GET',
        'success': function (data) {
            departamento_initial.append('<option value="" selected="selected">Seleccione Departamento</option>');
            for (var i = 0; i < data.departamentos.length; i++) {
              if (code_departamento == data.departamentos[i].codigo) {
                departamento_initial.append('<option selected="selected" value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              } else {
                departamento_initial.append('<option value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              }
            }
            if (code_departamento) {
              $('#id_shipping-departamento').trigger('change')
            }
            // provincia.change();
        }
    })
    $('#id_shipping-departamento').change(function(event) {
    /* Act on the event */
      var departamento = $(this).val();
      var provincia = $('#id_shipping-provincia')
      var distrito = $('#id_ubigeo')
      provincia.html('');
      distrito.html('');
      if (departamento) {
        $.ajax({
              'url': '{% url "ubigeo:api_provincias" %}' + '?departamento=' + departamento,
              'method': 'GET',
              'success': function (data) {
                  provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
                  for (var i = 0; i < data.provincias.length; i++) {
                    if (code_provincia == data.provincias[i].codigo) {
                      provincia.append('<option  selected="selected" value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    } else {
                      provincia.append('<option value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    }
                  }
                  if (code_provincia) {
                    $('#id_shipping-provincia').trigger('change')
                  }
                  // provincia.change();
              }
          })
      } else {
        provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
        distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
        code_provincia = ''
      }


    });
    $('#id_shipping-provincia').change(function(event) {
    /* Act on the event */
      var provincia = $(this).val();
      var distrito = $('#id_ubigeo')
      distrito.html('');
      $.ajax({
            'url': '{% url "ubigeo:api_distritos" %}' + '?provincia=' + provincia,
            'method': 'GET',
            'success': function (data) {
                distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
                for (var i = 0; i < data.distritos.length; i++) {
                  if (code_distrito == data.distritos[i].pk) {
                    distrito.append('<option selected="selected" value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  } else {
                    distrito.append('<option value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  }
                }
                code_distrito = ''
                // provincia.change();
            }
        })


    });
  });
</script>
{% endblock js %}

src/templates/system/my_address_edit.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main page-account">
  <div class="container">
    <div class="row">
    {% comment %}

      <div class="col-md-3 boxw">
        <div class="w-body">
          <div class="sidebar sidebar_account">
            <h3>Bienvenido</h3>
            <ul class='sidebar_account__info'>
              <li><a href="{% url 'web_system:account' %}">Información Personal
                 </a></li>
              <li><a href="{% url 'web_system:my_address' %}">Mis direcciones</a></li>
              <li><a href="{% url 'web_system:my_order' %}">Mis Ordenes</a></li>
            </ul>
          </div>
        </div>
      </div>
    {% endcomment %}
      <div class="col-md-10 col-md-offset-1">
        <div class="">
          <div class="page_account__title">
            Mi dirección
          </div>
          <div class="pages__content">
            <div class="row">
              <div class="col-md-12">
                <form action="" method='POST' class='page-account__form'>
                  {% csrf_token %}
                  <div class="row form-group">
                    <div class="col-md-6">
                      {{form.first_name.label_tag}}
                      {{form.first_name|add_class:'form-control'}}
                      <p class='text-danger'>{{form.first_name.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.last_name.label_tag}}
                      {{form.last_name|add_class:'form-control'}}
                      <p class='text-danger'>{{form.last_name.errors}}</p>
                    </div>

                    <div class="col-md-6">
                      {{form.type_document.label_tag}}
                      {{form.type_document|add_class:'form-control'}}
                      <p class='text-danger'>{{form.email.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.document.label_tag}}
                      {{form.document|add_class:'form-control'}}
                      <p class='text-danger'>{{form.document.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.phone.label_tag}}
                      {{form.phone|add_class:'form-control'}}
                      <p class='text-danger'>{{form.phone.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.address.label_tag}}
                      {{form.address|add_class:'form-control'}}
                      <p class='text-danger'>{{form.address.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.reference.label_tag}}
                      {{form.reference|add_class:'form-control'}}
                      <p class='text-danger'>{{form.reference.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      {{form.type_address.label_tag}}
                      {{form.type_address|add_class:'form-control'}}
                      <p class='text-danger'>{{form.type_address.errors}}</p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Departamento</label>
                      <select class="form-control" id='id_shipping-departamento'
                      name="departamento" >
                        <option value="">Seleccione Departamento</option>
                      </select>
                      <p></p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Provincia</label>
                      <select class="form-control" name="provincia" id="id_shipping-provincia">
                        <option value="">Seleccione Provincia</option>
                      </select>
                      <p></p>
                    </div>
                    <div class="col-md-6">
                      <label for="">Distrito</label>
                      {{form.ubigeo|add_class:'form-control'}}
                      <p class='text-danger'>{{form.ubigeo.errors}}</p>
                    </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                         <button class='btn btn--dark pull-right'>Guardar</button>
                      </div>
                  </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
{% block js %}
<script>
  jQuery(document).ready(function($) {
    var departamento_initial = $('#id_shipping-departamento')
    departamento_initial.html('')
    var code_departamento = '{{code_departamento}}'
    var code_provincia = '{{code_provincia}}'
    var code_distrito = '{{code_distrito}}'
    $.ajax({
        'url': '{% url "ubigeo:api_departamentos" %}',
        'method': 'GET',
        'success': function (data) {
            departamento_initial.append('<option value="" selected="selected">Seleccione Departamento</option>');
            for (var i = 0; i < data.departamentos.length; i++) {
              if (code_departamento == data.departamentos[i].codigo) {
                departamento_initial.append('<option selected="selected" value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              } else {
                departamento_initial.append('<option value="' + data.departamentos[i].codigo + '">' + data.departamentos[i].descripcion + '</option>');
              }
            }
            if (code_departamento) {
              $('#id_shipping-departamento').trigger('change')
            }
            // provincia.change();
        }
    })
    $('#id_shipping-departamento').change(function(event) {
    /* Act on the event */
      var departamento = $(this).val();
      var provincia = $('#id_shipping-provincia')
      var distrito = $('#id_ubigeo')
      provincia.html('');
      distrito.html('');
      if (departamento) {
        $.ajax({
              'url': '{% url "ubigeo:api_provincias" %}' + '?departamento=' + departamento,
              'method': 'GET',
              'success': function (data) {
                  provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
                  for (var i = 0; i < data.provincias.length; i++) {
                    if (code_provincia == data.provincias[i].codigo) {
                      provincia.append('<option  selected="selected" value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    } else {
                      provincia.append('<option value="' + data.provincias[i].codigo + '">' + data.provincias[i].descripcion + '</option>');
                    }
                  }
                  if (code_provincia) {
                    $('#id_shipping-provincia').trigger('change')
                  }
                  // provincia.change();
              }
          })
      } else {
        provincia.append('<option value="" selected="selected">Seleccione Provincia</option>');
        distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
        code_provincia = ''
      }


    });
    $('#id_shipping-provincia').change(function(event) {
    /* Act on the event */
      var provincia = $(this).val();
      var distrito = $('#id_ubigeo')
      distrito.html('');
      $.ajax({
            'url': '{% url "ubigeo:api_distritos" %}' + '?provincia=' + provincia,
            'method': 'GET',
            'success': function (data) {
                distrito.append('<option value="" selected="selected">Seleccione Distrito</option>');
                for (var i = 0; i < data.distritos.length; i++) {
                  if (code_distrito == data.distritos[i].pk) {
                    distrito.append('<option selected="selected" value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  } else {
                    distrito.append('<option value="' + data.distritos[i].pk + '">' + data.distritos[i].descripcion + '</option>');
                  }
                }
                code_distrito = ''
                // provincia.change();
            }
        })


    });
  });
</script>
{% endblock js %}

src/templates/system/my_order.html
{% extends "common/base.html" %}
{% load static thumbnail widget_tweaks %}
{% block css %}

{% endblock css %}
{% block content %}
<section class="main page-account">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="">
          <h2 class='page_account__title'>Mis Ordenes</h2>
          <div class="pages__content">
            <div class="row">
              {% for order in orders %}
              <div class="col-md-12">
                <div class="content_address">
                  <a href='{% url "web_system:my_order_detail" order.pk %}' class="">
                    <strong>{{order.get_type_status_display}} -   {{order.code}} </strong>
                    <p>total: {{order.total}}</p>
                  </a>
                </div>

              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 ">
        <div class="w-body">
          <div class="sidebar sidebar_account">
            <ul class='preguntas_frecuentes__sidebar preguntas_frecuentes__sidebar--account'>
              <li><a href="{% url 'web_system:account' %}">Información Personal
                 </a></li>
              <li><a href="{% url 'web_system:my_address' %}">Mis direcciones</a></li>
              <li><a class='active' href="{% url 'web_system:my_order' %}">Mis Ordenes</a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
{% endblock content %}
{% block js %}

{% endblock js %}